use strict";
exports.__esModule = true;
var chat_window_component_1 = require("./src/app/chat-window/chat-window.component");
exports.ChatBot = chat_window_component_1.ChatWindowComponent;
var data_service_1 = require("./src/app/services/data.service");
exports.ChatService = data_service_1.DataService;
var chat_input_component_1 = require("./src/app/chat-input/chat-input.component");
exports.ChatInput = chat_input_component_1.ChatInputComponent;
var chat_msg_component_1 = require("./src/app/chat-msg/chat-msg.component");
exports.ChatMsg = chat_msg_component_1.ChatMsgComponent;
